version: '3'
services:
  elasticsearch:
    image: nshou/elasticsearch-kibana
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
      - 5601:5601
    restart: on-failure  
    networks:
      - elastic
  jaeger:
    image: jaegertracing/all-in-one:1.21
    container_name: jaeger
    command: ["--es.server-urls=http://elasticsearch:9200"]
    environment:
      - node.name=jaeger
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_TAGS_AS_FIELDS_ALL=true
      - LOG_LEVEL=debug
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    restart: on-failure  
    depends_on:
      - elasticsearch  
    networks:
      - elastic
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - node.name=grafana
    ports:
      - 3000:3000
    restart: on-failure  
    networks:
      - elastic

networks:
  elastic:
    driver: bridge